# Generated by Django 3.0.6 on 2020-05-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.TextField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_running', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('code', models.TextField(help_text="Should be a 'difficult' string to guess", verbose_name='This is the unique token a participant has to use to authenticate')),
                ('state', models.IntegerField(choices=[(0, 'Registration pending'), (1, 'Participating'), (2, 'Winner')], default=(0, 'Registration pending'))),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Competition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipationsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Competition')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lottery.Participation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
