# Generated by Django 3.0.6 on 2020-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='participations',
            field=models.ManyToManyField(through='lottery.ParticipationsTable', to='lottery.Participation'),
        ),
    ]
