# Generated by Django 3.0.6 on 2020-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
