# Generated by Django 3.0.6 on 2020-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20200511_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='code',
            field=models.TextField(help_text="Should be a 'difficult' string to guess", verbose_name='This is the unique token a participant has to use, to signify he participates'),
        ),
    ]
